-- creacion de usuarios

-- LIGA: Principal
CREATE USER LIGA IDENTIFIED  BY LIGA;
GRANT DBA TO LIGA;

GRANT "AQ_USER_ROLE" TO LIGA WITH ADMIN OPTION ;
ALTER USER LIGA DEFAULT ROLE DBA,"AQ_USER_ROLE";

-- LIGA2: Backup Schema + Data

CREATE USER LIGA2 IDENTIFIED  BY LIGA;
GRANT DBA TO LIGA2;

GRANT "AQ_USER_ROLE" TO LIGA2 WITH ADMIN OPTION ;
ALTER USER LIGA2 DEFAULT ROLE DBA,"AQ_USER_ROLE";


-- LIGA3: Backup Schema
CREATE USER LIGA IDENTIFIED  BY LIGA;
GRANT DBA TO LIGA;

GRANT "AQ_USER_ROLE" TO LIGA3 WITH ADMIN OPTION ;
ALTER USER LIGA3 DEFAULT ROLE DBA,"AQ_USER_ROLE";