-- ==========================================================
Select * from VOTO;

CREATE VIEW VOTOSPRESIDENTE AS
Select  D.NOMBRE_DEPTO,M.NOMBRE_MUNI,P.NOMBRE_PART, SUM(VOTO_CANTIDAD) AS "No.Votos" from VOTO
INNER JOIN ACTA A2
    on VOTO.VOTO_MESA = A2.NUMERO_MESA
           and VOTO.VOTO_ELECCION = A2.TIPO_ELECCION
INNER JOIN PARTIDO P
    on P.CODIGO_PART = VOTO.VOTO_PARTIDO
INNER JOIN MUNICIPIO M
    on M.CODIGO_MUNI = A2.MUNICIPIO and M.DEPTO_MUNI = A2.DEPARTAMENTO
INNER JOIN DEPARTAMENTO D on
    D.CODIGO_DEPTO = M.DEPTO_MUNI
GROUP BY D.NOMBRE_DEPTO, M.NOMBRE_MUNI, P.NOMBRE_PART
ORDER BY D.NOMBRE_DEPTO, M.NOMBRE_MUNI, P.NOMBRE_PART
;

Select * from VOTOSPRESIDENTE;
GRANT SELECT ON ELECCIONES.VOTOSPRESIDENTE TO GUEST1;